apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-image
  labels:
    app: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debug-docker
        image: gcr.io/np-com-internal-thd/debug:latest  # use appropriate project ID

